name = "go-game-backend-free"
main = "workers/backend-free.js"
compatibility_date = "2024-01-01"
account_id = "6459dabf6604b2d6e887f95737cc0840"

[env.production]
workers_dev = false

[env.development]
workers_dev = true