name = "go-game-multiplayer"
main = "workers/websocket-proxy.js"
compatibility_date = "2024-01-01"

[env.production]
workers_dev = false
routes = [
  { pattern = "go-game.example.com/*", zone_name = "example.com" }
]

[env.development]
workers_dev = true

# Enable WebSocket support
[durable_objects]
bindings = [
  { name = "GAME_SESSIONS", class_name = "GameSession" }
]

[[migrations]]
tag = "v1"
new_classes = ["GameSession"]

# Environment variables
[vars]
BACKEND_URL = "http://localhost:3000"

[env.production.vars]
BACKEND_URL = "https://your-backend-server.com"