# Consolidated Wrangler configuration for Go Game
# Handles both frontend (Pages) and backend (Workers) deployments

name = "go-game"
account_id = "6459dabf6604b2d6e887f95737cc0840"
compatibility_date = "2024-01-01"

# Backend Worker with Durable Objects (SQLite)
main = "workers/backend-durable-sqlite.js"

[env.production]
name = "go-game-backend"
workers_dev = true

[env.production.durable_objects]
bindings = [
  { name = "GAME_COORDINATOR", class_name = "GameCoordinator" }
]

[env.development]
name = "go-game-backend-dev"
workers_dev = true

[durable_objects]
bindings = [
  { name = "GAME_COORDINATOR", class_name = "GameCoordinator" }
]

# SQLite migrations for free tier
[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameCoordinator"]

# Build configuration
[build]
command = ""

# Pages configuration for frontend
[site]
bucket = "./public"

# Environment-specific configurations
# Routes are configured separately in dashboard or via wrangler publish

[env.production.vars]
FRONTEND_URL = "https://go-game-multiplayer.pages.dev"

[env.development.vars]
FRONTEND_URL = "http://localhost:3000"

# Deployment aliases
[alias]
backend = "wrangler deploy --env production"
frontend = "wrangler pages deploy public --project-name go-game-multiplayer"
all = "npm run deploy:all"