name = "go-game-backend"
main = "workers/backend-simple.js"
compatibility_date = "2024-01-01"

[env.production]
workers_dev = false

[env.development]
workers_dev = true

# Durable Objects binding
[durable_objects]
bindings = [
  { name = "GAME_COORDINATOR", class_name = "GameCoordinator" }
]

[[migrations]]
tag = "v1"
new_classes = ["GameCoordinator"]

# Build configuration
[build]
command = ""