name = "go-game-proxy"
main = "workers/simple-proxy.js"
compatibility_date = "2024-01-01"

[env.production]
workers_dev = false

[env.development]
workers_dev = true

# Environment variables
[vars]
BACKEND_URL = "http://localhost:3000"

[env.production.vars]
BACKEND_URL = "https://your-backend-server.com"